version: "3"

services:
  cdac:
    image: samagragovernance/cdac-service:latest
    restart: always
    environment:
      USERNAME: "${USERNAME}"
      SENDER_ID: "${SENDER_ID}"
      PASSWORD: "${PASSWORD}"
      SECURE_KEY: "${SECURE_KEY}"
    ports:
      - "127.0.0.1:8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://cdac:8080/api"]
      interval: 2s
      timeout: 5s
      retries: 20